name: alvys3
description: Alvys mobile driver app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.4
  flutter_secure_storage: ^6.1.0
  page_transition: ^2.0.5
  rflutter_alert: ^2.0.4
  google_fonts: ^3.0.1
  http: ^0.13.4
  simple_speed_dial: ^0.1.7
  equatable: ^2.0.3
  flutter_riverpod: ^2.1.1
  riverpod_annotation: ^1.0.6
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0  
  dio: ^4.0.6
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.1.1
  reactive_forms: ^12.0.0
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  go_router: ^5.0.5
  pinput: ^2.2.16
  thumbnailer: ^2.0.2
  file_previewer: ^0.0.5
  auto_size_text: ^3.0.0
  flutter_cache_manager: ^3.3.0
  pdf_viewer_plugin: ^2.0.1
  flutter_gen: ^5.1.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  icons_launcher: ^2.0.6
  freezed: ^2.0.3
  freezed_annotation: ^2.0.3
  build_runner: ^2.1.10
  riverpod_generator: ^1.0.6


flutter_icons:
  android: true  
  ios: true
  image_path: "assets/logo.png"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

assets:
  - .env
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
