name: alvys3
description: Alvys mobile driver app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.32+292

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.16
  page_transition: ^2.0.5
  rflutter_alert: ^2.0.4
  google_fonts: ^6.1.0
  http: ^1.1.0
  simple_speed_dial: ^0.1.7
  equatable: ^2.0.3
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.0.2
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  dio: ^5.1.1
  internet_connection_checker: ^3.0.1
  pretty_dio_logger: ^1.1.1
  intl: ^0.20.1
  flutter_spinkit: ^5.1.0
  go_router: ^14.7.1
  pinput: ^5.0.0
  auto_size_text: ^3.0.0
  flutter_cache_manager: ^3.3.0
  flutter_pdfview: ^1.3.2
  flutter_gen: ^5.1.0+1
  mask_text_input_formatter: ^2.4.0
  share_plus: ^10.0.0
  path_provider: ^2.0.11
  cross_file: ^0.3.3+2
  fade_shimmer: ^2.2.0
  device_info_plus: ^11.1.0
  url_launcher: ^6.1.7
  envied: ^1.0.0
  package_info_plus: ^8.0.0
  permission_handler: ^11.0.0
  app_settings: 5.1.1
  flutter_genius_scan: ^5.1.3
  image_picker: ^1.1.2
  material_symbols_icons: ^4.2668.0
  google_maps_flutter: ^2.10.0
  coder_matthews_extensions: ^1.12.1
  lottie: ^3.1.0
  signalr_netcore: ^1.4.0
  logging: ^1.2.0
  flutter_widget_from_html: ^0.15.1
  geolocator: ^13.0.1
  azure_application_insights: ^5.0.1
  uuid: ^4.5.1
  firebase_core: ^3.8.1
  firebase_analytics: ^11.3.6
  firebase_crashlytics: ^4.2.0
  firebase_remote_config: ^5.2.0
  flexible_polyline:
    git:
      url: https://github.com/heremaps/flexible-polyline.git
      path: dart
  shared_preferences: ^2.2.1
  connectivity_plus: ^6.0.1
  upgrader: ^11.0.0
  app_tracking_transparency: ^2.0.4
  flutter_image_compress: ^2.3.0
  ua_client_hints: ^1.4.1
  launchdarkly_flutter_client_sdk: ^4.9.0
  opentelemetry: ^0.18.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.0.3
  build_runner: ^2.3.3
  riverpod_generator: ^2.6.3
  flutter_launcher_icons: ^0.14.1
  envied_generator: ^1.0.0
  riverpod_lint: ^2.6.3
  analyzer: ^6.11.0
  posthog_flutter: ^4.5.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env
    - assets/lottie/green_pulse.json
    - assets/
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Alvys3Icons
      fonts:
        - asset: assets/fonts/Alvys3Icons.ttf
    - family: AlvysMobileIcons
      fonts:
        - asset: assets/fonts/AlvysMobileIcons.ttf
  # fonts:
  #   - family: Alvys3Icons
  #     fonts:
  #       - asset: assets/fonts/Alvys3Icons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
