name: alvys3
description: Alvys mobile driver app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.16
  flutter_secure_storage: ^8.0.0
  page_transition: ^2.0.5
  rflutter_alert: ^2.0.4
  google_fonts: ^4.0.4
  http: ^0.13.6
  simple_speed_dial: ^0.1.7
  equatable: ^2.0.3
  flutter_riverpod: ^2.3.3
  riverpod_annotation: ^2.0.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  dio: ^5.1.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.1.1
  intl: ^0.18.1
  flutter_spinkit: ^5.1.0
  go_router: ^10.0.0
  pinput: ^3.0.0
  auto_size_text: ^3.0.0
  flutter_cache_manager: ^3.3.0
  pdf_viewer_plugin: ^2.0.1
  flutter_gen: ^5.1.0+1
  mask_text_input_formatter: ^2.4.0
  share_plus: ^7.0.2
  path_provider: ^2.0.11
  cross_file: ^0.3.3+2
  fade_shimmer: ^2.2.0
  device_info_plus: ^9.0.2
  url_launcher: ^6.1.7
  envied: ^0.3.0
  package_info_plus: ^4.0.2
  permission_handler: ^10.2.0
  app_settings: ^5.0.0
  flutter_genius_scan: ^4.12.0
  image_picker: ^1.0.1
  material_symbols_icons: ^4.2668.0
  google_maps_flutter: ^2.4.0
  coder_matthews_extensions: ^1.1.0
  lottie: ^2.6.0
  signalr_netcore: ^1.3.6
  logging: ^1.2.0
  flutter_widget_from_html: ^0.10.4
  geolocator: ^10.0.0
  # azure_application_insights: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  icons_launcher: ^2.0.6
  freezed: ^2.0.3
  freezed_annotation: ^2.0.3
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.6
  flutter_launcher_icons: ^0.13.1
  envied_generator: ^0.3.0
  riverpod_lint: ^2.0.1

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env
    - assets/lottie/green_pulse.json
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Alvys3Icons
      fonts:
        - asset: assets/fonts/Alvys3Icons.ttf
  # fonts:
  #   - family: Alvys3Icons
  #     fonts:
  #       - asset: assets/fonts/Alvys3Icons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
