// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeT-XdjueUULQNs14qFPWewpw35fWU-pw',
    appId: '1:459046327856:android:09a5f6859e29e41c47fff5',
    messagingSenderId: '459046327856',
    projectId: 'alvys-1e881',
    databaseURL: 'https://alvys-1e881.firebaseio.com',
    storageBucket: 'alvys-1e881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhue_HTrZiQWQclE6BWKJS8mU18unX7to',
    appId: '1:459046327856:ios:e5604949989c4c1647fff5',
    messagingSenderId: '459046327856',
    projectId: 'alvys-1e881',
    databaseURL: 'https://alvys-1e881.firebaseio.com',
    storageBucket: 'alvys-1e881.appspot.com',
    iosClientId: '459046327856-0c0qd0sqdngm6mlmibtnc45p3fbti82m.apps.googleusercontent.com',
    iosBundleId: 'io.alvys.app',
  );
}
