

default_platform(:android)

platform :android do


  # Define lane for building the app
  desc "Build the Android app"
  lane :build do |options|
    flavor = options[:flavor] || 'dev'  # Default to 'dev' flavor if not specified
    sh "flutter build appbundle --flavor=#{flavor} --target=lib/#{flavor}.dart"
  end

  # Define lanes for each flavor

  desc "Build the Development"
  lane :build_dev do
    build(flavor: 'dev')
  end

  desc "Build for QA"
  lane :build_qa do
    build(flavor: 'qa')
  end

  desc "Build the Production"
  lane :build_prod do
    build(flavor: 'prod')
  end


  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


  

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
