/// Flutter icons Alvys3Icons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Alvys3Icons
///      fonts:
///       - asset: fonts/Alvys3Icons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Alvys3Icons {
  Alvys3Icons._();

  static const _kFontFam = 'Alvys3Icons';
  static const String? _kFontPkg = null;

  static const IconData homeIco = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationIcon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trackIcon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tripIcon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deliveryTruck = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
